version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: go run main.go
  redis:
    image: redis
  db:
    image: mariadb:10.5
    restart: always
    ports:
    - 33060:3306
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "web"

